apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: crud-app
type: Opaque
data:
  db_password: QXAwMHJQYSQkdzByZCE=
  db_username: cG9zdGdyZXM=
  db_name: cG9zdGdyZXM=
  db_address: cG9zdGdyZXMtc3Zj
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployment
    type: backend
  name: backend-deployment
  namespace: crud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      type: backend
  template:
    metadata:
      labels:
        app: backend
        type: backend
    spec:
      containers:
      - image: final_assignment-backend
        imagePullPolicy: Never
        name: backend
        resources:
          limits:
            memory: "500Mi"
            cpu: "400m"
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: crud-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: backend
    type: backend
  type: ClusterIP